// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Miguel_P1_AP2.DAL;

namespace Miguel_P1_AP2.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("Miguel_P1_AP2.Models.Articulos", b =>
                {
                    b.Property<int>("ArticuloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Existencia")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ArticuloId");

                    b.ToTable("Articulos");

                    b.HasData(
                        new
                        {
                            ArticuloId = 1,
                            Departamento = "Tecnologia",
                            DepartamentoId = 1,
                            Descripcion = "Iphone 2g",
                            Existencia = 2,
                            Precio = 4000m,
                            Referencia = "Tecn"
                        },
                        new
                        {
                            ArticuloId = 2,
                            Departamento = "Tecnologia",
                            DepartamentoId = 1,
                            Descripcion = "Iphone 3g",
                            Existencia = 3,
                            Precio = 5000m,
                            Referencia = "Tecn"
                        },
                        new
                        {
                            ArticuloId = 3,
                            Departamento = "Ferreteria",
                            DepartamentoId = 2,
                            Descripcion = "Tornillo Grande",
                            Existencia = 100,
                            Precio = 15m,
                            Referencia = "Tool"
                        });
                });

            modelBuilder.Entity("Miguel_P1_AP2.Models.Departamentos", b =>
                {
                    b.Property<int>("DepartamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DepartamentoId");

                    b.ToTable("Departamentos");

                    b.HasData(
                        new
                        {
                            DepartamentoId = 1,
                            Descripcion = "Tecnologia"
                        },
                        new
                        {
                            DepartamentoId = 2,
                            Descripcion = "Ferreteria"
                        });
                });

            modelBuilder.Entity("Miguel_P1_AP2.Models.Pedidos", b =>
                {
                    b.Property<int>("PedidoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArticuloId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasColumnType("TEXT");

                    b.HasKey("PedidoId");

                    b.ToTable("Pedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
